/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 model2.gltf --tranform 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model2(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/model2.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Start animations if any exist
    if (animations.length > 0) {
      // Play the first animation by default
      const animationName = Object.keys(actions)[0]
      if (animationName) {
        actions[animationName].reset().play()
      }
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null} scale={.6} position-y={-5}>
      <group name="Scene">
        <mesh name="Shape6__0003" geometry={nodes.Shape6__0003.geometry} material={materials['Scene_-_Root']} position={[7.41, 24.976, -11.543]} rotation={[Math.PI, 0, Math.PI]} scale={[1.169, 1.275, 1.51]} />
        <group name="Panda_Belt002" position={[1.3, -2.744, -2.247]} rotation={[0, 0.067, 0]} scale={0.165}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['panda Belt.004']} />
          <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials['Material.001']} />
          <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials[' Heart Ballon']} />
          <mesh name="Circle002_3" geometry={nodes.Circle002_3.geometry} material={materials['panda.005']} />
        </group>
        <group name="particle000" position={[1.432, 0, 6.619]} scale={0.785}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle001" position={[-3.769, 27.053, -7.275]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle002" position={[-2.477, 24.036, 2.958]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle003" position={[7.495, 21.568, 5.95]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle004" position={[-4.005, 12.033, -8.336]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle005" position={[5.243, 3.261, 7.101]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle006" position={[1.696, 20.185, -7.411]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle007" position={[-1.403, 25.772, 11.739]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle008" position={[-5.582, 26.804, 5.199]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle009" position={[5.959, 22.169, 3.101]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle010" position={[-1.665, 25.163, 8.593]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle011" position={[2.746, 28.549, -5.281]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle012" position={[7.452, 22.607, -2.492]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle013" position={[8.283, 17.648, -0.894]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle014" position={[-4.191, 7.044, -8.205]} scale={0.001}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Balloon5.001']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.lace} />
        </group>
        <group name="particle030" position={[-4.429, 0, 7.351]} scale={1.168}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle031" position={[-3.438, 27.221, -8.578]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle032" position={[7.204, 24.669, 3.14]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle033" position={[6.056, 25.526, 6.96]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle034" position={[-2.071, 23.892, -9.706]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle035" position={[4.075, 23.6, 5.337]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle036" position={[7.129, 12.849, -7.615]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle037" position={[3.244, 5.031, 8.123]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle038" position={[-7.255, 26.898, 6.724]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <group name="particle039" position={[-0.019, 10.908, 4.696]} scale={0.001}>
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials.Balloon3} />
          <mesh name="Sphere017_1" geometry={nodes.Sphere017_1.geometry} material={materials.lace} />
        </group>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[0.751, 24.992, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.532} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-6.439, 16.831, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.249} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.004']} position={[3.822, 18.412, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.929} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.004']} position={[5.299, 22.494, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.063} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.004']} position={[-0.828, 20.239, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.051} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.004']} position={[5.412, 14.104, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.063} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.004']} position={[-2.978, 13.317, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.094} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.004']} position={[-7.395, 9.961, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.32} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.004']} position={[9.912, 6.658, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.32} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.004']} position={[-0.751, 5.628, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.886} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.004']} position={[-8.904, 7.077, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.924} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.004']} position={[5.316, 5.084, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.271} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.004']} position={[9.423, 1.523, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.331} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.004']} position={[1.636, 2.358, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.788} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.004']} position={[-2.151, 1.955, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.585} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['Material.004']} position={[-10.221, 2.363, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.057} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Material.004']} position={[-10.689, 13.394, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.185} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Material.004']} position={[3.441, 28.488, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Material.004']} position={[-1.996, 27.692, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.004']} position={[-3.479, 15.816, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Material.004']} position={[-5.508, 13.214, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.004']} position={[-6.623, 4.456, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['Material.004']} position={[6.251, 10.404, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.915} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Material.004']} position={[9.9, 19.659, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.247} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials['Material.004']} position={[-5.241, 25.012, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.93} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Material.004']} position={[-10.016, 19.938, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.93} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials['Material.004']} position={[2.026, 11.888, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.436} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['Material.004']} position={[-1.343, 10.147, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.986} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['Material.004']} position={[-11.856, 25.27, -12]} rotation={[Math.PI / 2, 0, 0]} scale={1.249} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials['Material.004']} position={[10.366, 13.064, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.808} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials['Material.004']} position={[11.032, 22.952, -12]} rotation={[Math.PI / 2, 0, 0]} scale={0.808} />
        <mesh name="particle015" geometry={nodes.particle015.geometry} material={materials['default']} position={[8.014, 30.454, 6.058]} scale={2.39} />
        <mesh name="particle016" geometry={nodes.particle016.geometry} material={materials['default']} position={[3.1, 3.655, -7.688]} scale={0.001} />
        <mesh name="particle017" geometry={nodes.particle017.geometry} material={materials['default']} position={[-13.745, 6.207, 1.075]} scale={0.001} />
        <mesh name="particle018" geometry={nodes.particle018.geometry} material={materials['default']} position={[9.89, 9.66, -4.09]} scale={0.001} />
        <mesh name="particle019" geometry={nodes.particle019.geometry} material={materials['default']} position={[7.265, 15.077, 6.694]} scale={0.001} />
        <mesh name="particle020" geometry={nodes.particle020.geometry} material={materials['default']} position={[-6.006, 20.236, 6.282]} scale={0.001} />
        <mesh name="particle021" geometry={nodes.particle021.geometry} material={materials['default']} position={[10.536, 25.584, -8.573]} scale={0.001} />
        <mesh name="particle022" geometry={nodes.particle022.geometry} material={materials['default']} position={[3.1, 3.368, -7.673]} scale={0.001} />
        <mesh name="particle023" geometry={nodes.particle023.geometry} material={materials['default']} position={[-13.542, 8.119, 1.04]} scale={0.001} />
        <mesh name="particle024" geometry={nodes.particle024.geometry} material={materials['default']} position={[-4.663, 5.778, -7.684]} scale={0.001} />
        <mesh name="particle025" geometry={nodes.particle025.geometry} material={materials['default']} position={[7.267, 5.889, 6.908]} scale={0.001} />
        <mesh name="particle026" geometry={nodes.particle026.geometry} material={materials['default']} position={[-5.852, 8.856, 5.621]} scale={0.001} />
        <mesh name="particle027" geometry={nodes.particle027.geometry} material={materials['default']} position={[-9.465, 14.654, 5.078]} scale={0.001} />
        <mesh name="particle028" geometry={nodes.particle028.geometry} material={materials['default']} position={[2.616, 19.441, 6.843]} scale={0.001} />
        <mesh name="particle029" geometry={nodes.particle029.geometry} material={materials['default']} position={[8.878, 25.14, 0.531]} scale={0.001} />
        <group name="particle040" position={[9.458, 0, 1.808]} scale={0.721}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle041" position={[-7.286, 25.479, -9.748]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle042" position={[14.761, 30.608, -1.868]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle043" position={[8.077, 38.871, -8.272]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle044" position={[-6.147, 11.922, -6.179]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle045" position={[9.773, 1.968, 2.894]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle046" position={[-6.842, 38.314, -9.37]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle047" position={[2.217, 51.291, -5.863]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle048" position={[9.252, 21.275, -7.379]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
        <group name="particle049" position={[-8.819, 18.144, -7.429]} scale={0.001}>
          <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials.balloon2} />
          <mesh name="Sphere023_1" geometry={nodes.Sphere023_1.geometry} material={materials.lace} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/model2.gltf')
